/* Generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "blinky.v:1.1-23.10" *)
module blinky(clki, led1, led2, led3, led4, led5);
  (* src = "blinky.v:11.10-11.13" *)
  wire clk;
  (* src = "blinky.v:2.12-2.16" *)
  input clki;
  (* src = "blinky.v:10.16-10.23" *)
  wire [25:0] counter;
  (* src = "blinky.v:3.12-3.16" *)
  output led1;
  (* src = "blinky.v:4.12-4.16" *)
  output led2;
  (* src = "blinky.v:5.12-5.16" *)
  output led3;
  (* src = "blinky.v:6.12-6.16" *)
  output led4;
  (* src = "blinky.v:7.12-7.16" *)
  output led5;
  (* force_downto = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" *)
  wire [25:0] led5_SB_CARRY_I1_CO;
  (* force_downto = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:33.26-33.27" *)
  wire [25:0] led5_SB_LUT4_I2_O;
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:13.11-16.6" *)
  SB_GB clk_gb (
    .GLOBAL_BUFFER_OUTPUT(clk),
    .USER_SIGNAL_TO_GLOBAL_BUFFER(clki)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[20]),
    .Q(counter[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_1 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[19]),
    .Q(counter[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_10 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[10]),
    .Q(counter[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_11 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[9]),
    .Q(counter[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_12 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[8]),
    .Q(counter[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_13 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[7]),
    .Q(counter[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_14 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[6]),
    .Q(counter[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_15 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[5]),
    .Q(counter[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_16 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[4]),
    .Q(counter[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_17 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[3]),
    .Q(counter[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_18 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[2]),
    .Q(counter[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_19 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[1]),
    .Q(counter[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_2 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[18]),
    .Q(counter[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_20 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[0]),
    .Q(counter[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_3 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[17]),
    .Q(counter[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_4 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[16]),
    .Q(counter[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_5 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[15]),
    .Q(counter[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_6 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[14]),
    .Q(counter[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_7 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[13]),
    .Q(counter[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_8 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[12]),
    .Q(counter[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF counter_SB_DFF_Q_9 (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[11]),
    .Q(counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF led1_SB_DFF_Q (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[25]),
    .Q(led1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led1_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(led1),
    .I3(led5_SB_CARRY_I1_CO[25]),
    .O(led5_SB_LUT4_I2_O[25])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led2_SB_CARRY_I1 (
    .CI(led5_SB_CARRY_I1_CO[24]),
    .CO(led5_SB_CARRY_I1_CO[25]),
    .I0(1'h0),
    .I1(led2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF led2_SB_DFF_Q (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[24]),
    .Q(led2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led2_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(led2),
    .I3(led5_SB_CARRY_I1_CO[24]),
    .O(led5_SB_LUT4_I2_O[24])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led3_SB_CARRY_I1 (
    .CI(led5_SB_CARRY_I1_CO[23]),
    .CO(led5_SB_CARRY_I1_CO[24]),
    .I0(1'h0),
    .I1(led3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF led3_SB_DFF_Q (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[23]),
    .Q(led3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led3_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(led3),
    .I3(led5_SB_CARRY_I1_CO[23]),
    .O(led5_SB_LUT4_I2_O[23])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led4_SB_CARRY_I1 (
    .CI(led5_SB_CARRY_I1_CO[22]),
    .CO(led5_SB_CARRY_I1_CO[23]),
    .I0(1'h0),
    .I1(led4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF led4_SB_DFF_Q (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[22]),
    .Q(led4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led4_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(led4),
    .I3(led5_SB_CARRY_I1_CO[22]),
    .O(led5_SB_LUT4_I2_O[22])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1 (
    .CI(led5_SB_CARRY_I1_CO[21]),
    .CO(led5_SB_CARRY_I1_CO[22]),
    .I0(1'h0),
    .I1(led5)
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO (
    .CI(led5_SB_CARRY_I1_CO[9]),
    .CO(led5_SB_CARRY_I1_CO[10]),
    .I0(1'h0),
    .I1(counter[9])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_1 (
    .CI(led5_SB_CARRY_I1_CO[8]),
    .CO(led5_SB_CARRY_I1_CO[9]),
    .I0(1'h0),
    .I1(counter[8])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_10 (
    .CI(led5_SB_CARRY_I1_CO[19]),
    .CO(led5_SB_CARRY_I1_CO[20]),
    .I0(1'h0),
    .I1(counter[19])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_11 (
    .CI(led5_SB_CARRY_I1_CO[18]),
    .CO(led5_SB_CARRY_I1_CO[19]),
    .I0(1'h0),
    .I1(counter[18])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_12 (
    .CI(led5_SB_CARRY_I1_CO[17]),
    .CO(led5_SB_CARRY_I1_CO[18]),
    .I0(1'h0),
    .I1(counter[17])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_13 (
    .CI(led5_SB_CARRY_I1_CO[16]),
    .CO(led5_SB_CARRY_I1_CO[17]),
    .I0(1'h0),
    .I1(counter[16])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_14 (
    .CI(led5_SB_CARRY_I1_CO[15]),
    .CO(led5_SB_CARRY_I1_CO[16]),
    .I0(1'h0),
    .I1(counter[15])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_15 (
    .CI(led5_SB_CARRY_I1_CO[14]),
    .CO(led5_SB_CARRY_I1_CO[15]),
    .I0(1'h0),
    .I1(counter[14])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_16 (
    .CI(led5_SB_CARRY_I1_CO[13]),
    .CO(led5_SB_CARRY_I1_CO[14]),
    .I0(1'h0),
    .I1(counter[13])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_17 (
    .CI(led5_SB_CARRY_I1_CO[12]),
    .CO(led5_SB_CARRY_I1_CO[13]),
    .I0(1'h0),
    .I1(counter[12])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_18 (
    .CI(led5_SB_CARRY_I1_CO[11]),
    .CO(led5_SB_CARRY_I1_CO[12]),
    .I0(1'h0),
    .I1(counter[11])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_19 (
    .CI(led5_SB_CARRY_I1_CO[10]),
    .CO(led5_SB_CARRY_I1_CO[11]),
    .I0(1'h0),
    .I1(counter[10])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_2 (
    .CI(led5_SB_CARRY_I1_CO[7]),
    .CO(led5_SB_CARRY_I1_CO[8]),
    .I0(1'h0),
    .I1(counter[7])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_3 (
    .CI(led5_SB_CARRY_I1_CO[6]),
    .CO(led5_SB_CARRY_I1_CO[7]),
    .I0(1'h0),
    .I1(counter[6])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_4 (
    .CI(led5_SB_CARRY_I1_CO[5]),
    .CO(led5_SB_CARRY_I1_CO[6]),
    .I0(1'h0),
    .I1(counter[5])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_5 (
    .CI(led5_SB_CARRY_I1_CO[4]),
    .CO(led5_SB_CARRY_I1_CO[5]),
    .I0(1'h0),
    .I1(counter[4])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_6 (
    .CI(led5_SB_CARRY_I1_CO[3]),
    .CO(led5_SB_CARRY_I1_CO[4]),
    .I0(1'h0),
    .I1(counter[3])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_7 (
    .CI(led5_SB_CARRY_I1_CO[2]),
    .CO(led5_SB_CARRY_I1_CO[3]),
    .I0(1'h0),
    .I1(counter[2])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_8 (
    .CI(led5_SB_CARRY_I1_CO[20]),
    .CO(led5_SB_CARRY_I1_CO[21]),
    .I0(1'h0),
    .I1(counter[20])
  );
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY led5_SB_CARRY_I1_CO_SB_CARRY_CO_9 (
    .CI(counter[0]),
    .CO(led5_SB_CARRY_I1_CO[2]),
    .I0(1'h0),
    .I1(counter[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:18.5-20.8|/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF led5_SB_DFF_Q (
    .C(clk),
    .D(led5_SB_LUT4_I2_O[21]),
    .Q(led5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(led5),
    .I3(led5_SB_CARRY_I1_CO[21]),
    .O(led5_SB_LUT4_I2_O[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(counter[0]),
    .O(led5_SB_LUT4_I2_O[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[10]),
    .I3(led5_SB_CARRY_I1_CO[10]),
    .O(led5_SB_LUT4_I2_O[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_10 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[20]),
    .I3(led5_SB_CARRY_I1_CO[20]),
    .O(led5_SB_LUT4_I2_O[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_11 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[1]),
    .I3(counter[0]),
    .O(led5_SB_LUT4_I2_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_12 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[19]),
    .I3(led5_SB_CARRY_I1_CO[19]),
    .O(led5_SB_LUT4_I2_O[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_13 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[18]),
    .I3(led5_SB_CARRY_I1_CO[18]),
    .O(led5_SB_LUT4_I2_O[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_14 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[17]),
    .I3(led5_SB_CARRY_I1_CO[17]),
    .O(led5_SB_LUT4_I2_O[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_15 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[16]),
    .I3(led5_SB_CARRY_I1_CO[16]),
    .O(led5_SB_LUT4_I2_O[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_16 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[15]),
    .I3(led5_SB_CARRY_I1_CO[15]),
    .O(led5_SB_LUT4_I2_O[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_17 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[14]),
    .I3(led5_SB_CARRY_I1_CO[14]),
    .O(led5_SB_LUT4_I2_O[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_18 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[13]),
    .I3(led5_SB_CARRY_I1_CO[13]),
    .O(led5_SB_LUT4_I2_O[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_19 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[12]),
    .I3(led5_SB_CARRY_I1_CO[12]),
    .O(led5_SB_LUT4_I2_O[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[9]),
    .I3(led5_SB_CARRY_I1_CO[9]),
    .O(led5_SB_LUT4_I2_O[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_20 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[11]),
    .I3(led5_SB_CARRY_I1_CO[11]),
    .O(led5_SB_LUT4_I2_O[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[8]),
    .I3(led5_SB_CARRY_I1_CO[8]),
    .O(led5_SB_LUT4_I2_O[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[7]),
    .I3(led5_SB_CARRY_I1_CO[7]),
    .O(led5_SB_LUT4_I2_O[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_5 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[6]),
    .I3(led5_SB_CARRY_I1_CO[6]),
    .O(led5_SB_LUT4_I2_O[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_6 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[5]),
    .I3(led5_SB_CARRY_I1_CO[5]),
    .O(led5_SB_LUT4_I2_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_7 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[4]),
    .I3(led5_SB_CARRY_I1_CO[4]),
    .O(led5_SB_LUT4_I2_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_8 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[3]),
    .I3(led5_SB_CARRY_I1_CO[3]),
    .O(led5_SB_LUT4_I2_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky.v:19.20-19.31|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) led5_SB_LUT4_I2_O_SB_LUT4_O_9 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(counter[2]),
    .I3(led5_SB_CARRY_I1_CO[2]),
    .O(led5_SB_LUT4_I2_O[2])
  );
  assign led5_SB_CARRY_I1_CO[1:0] = { counter[0], 1'h0 };
  assign counter[25:21] = { led1, led2, led3, led4, led5 };
endmodule
