/* Generated by Yosys 0.9+4081 (git sha1 862e84eb, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "mux.v:1.1-6.10" *)
module mux(a, b, s, y);
  (* src = "mux.v:2.11-2.12" *)
  wire _0_;
  (* src = "mux.v:2.13-2.14" *)
  wire _1_;
  (* src = "mux.v:2.15-2.16" *)
  wire _2_;
  (* src = "mux.v:3.12-3.13" *)
  wire _3_;
  (* src = "mux.v:2.11-2.12" *)
  input a;
  (* src = "mux.v:2.13-2.14" *)
  input b;
  (* src = "mux.v:2.15-2.16" *)
  input s;
  (* src = "mux.v:3.12-3.13" *)
  output y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_1_),
    .A1(_0_),
    .S(_2_),
    .X(_3_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign _2_ = s;
  assign y = _3_;
endmodule
